kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apache-manager
  namespace: apache
rules:
  - apiGroups: ["","*", "apps", "rbac.authorization.k8s.io", "batch","extensions","clusterrolebindings","apiextensions.k8s.io","policy","storage.k8s.io","networking.k8s.io","coordination.k8s.io"]
    resources: [ "deployments", "pods", "services","statefulsets","daemonsets","replicasets","jobs","cronjobs","configmaps","secrets","namespaces","persistentcolumeclaims","ingresses","roles","rolebindings","clusterroles","clusterrolebindings"]
    verbs: ["get", "list","watch", "create", "update", "patch", "delete","deletecollection","impersonate", "escalate","bind","use"]
    