apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: nginx
spec:
  containers:
  - name: mginx-container
    image: nginx:latest
    ports:
      - containerPort: 80
  tolerations:    # tolerence use here 
    - key: "prod"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

