kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: devopsbatches.cloudwithyuvi.com
spec:
  group: cloudwithyuvi.com
  names:
    plural: devopsbatches
    singular: devopsbatch
    kind: DevOpsBatch
    shortNames:
        - cwy
        - devops
        - batches
  scope: Namespaced
  version:
  - name: v1
    served: true 
    storage: true
    schema: 
      openAPIV3schema:
        type: object
        properties: 
          spec: 
            type: object
            properties:
              name:
                type: string
                description: "This is the name of custom resource for cwy"
              duration:
                type: string
                description: "This is duration of custom resource for cwy"
              mode: 
                type: string
                description: "This is mode of custom resource fro cwy"
