kind: Secret
apiVersion: v1
metadata:
  name: mysql-secret
  namespace: mysql
data:
  MYSQL_ROOT_PASSWORD: root

  # convert root to base64 encoded - run [ echo "yourpassowrd" | base64 on your local system]
