kind: Deployment
apiVersion: apps/v1
metadata:
  name: notes-app-deploy
  namespace: notes-app
  labels:
    app: notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      name: notes-app-deploy
      labels:
        app: nginx
    spec:
      containers:
      - name: notes-app
        image: jarvuy0555/notes-app-k8s
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:    # this probe help to check yoru app is live or not 
          httpGet:
            path: /
            port: 8000
        readinessProbe:    # this probe help to check your pod is ready or not
          httpGet:
            path: /
            port: 8000

            
