apiVersion: v1
kind: Pod
metadata:
  name: load-generator
  namespace: apache
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'while true; do wget -q -O- http://apahce-service.apache.svc.cluster.local; done']
