apiVersion: v1
kind: PersistenVolumeClaim
metadata:
  name: local-pvc
  namespace: nginx
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-system
