apiVersion: v1
kind: Service
metadata:
  name: notes-app-servcie
  namespace: notes-app
spec:
  selector:
    app: notes-app
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
